# providerxyz :: docker-compose

networks:
  providerxyz_localhost:

services:
  web:
    deploy:
      replicas: 1
    image: providerxyz
    networks:
      - providerxyz_localhost
    ports:
      - 10080:80
      - 10443:443

version: '3.7'
