# addressxyz :: docker-compose

networks:
  addressxyz_localhost:

services:
  api:
    depends_on:
      - db
    deploy:
      replicas: 1
    image: addressxyz
    networks:
      - addressxyz_localhost
    ports:
      - 10080:80
      - 10443:443

  db:
    deploy:
      replicas: 1
    image: postgres
    networks:
      - addressxyz_localhost

version: '3.7'
